### ISSUE TITLE
Default versions of Python does not match jupyter image

### ISSUE THREAD

**Issue by ogrisel** [dask/dask-docker#2]
When using this container as part of the [dask-distributed helm chart](https://github.com/kubernetes/charts/tree/master/stable/dask-distributed) one faces the issue of inconsistent python versions:

- 2.7 for this image
- 3.5 (currently) for jupyter

I think we should stop providing 2.7 by default and instead use Python 3.6 by default for this image. Furthermore it would be great to find way to pass an `environment.yml` that would be used to initialise the images both for jupyter and the dask workers (and scheduler) maybe using the [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) feature of Dockerfile so that all containers share compatible versions of Python and shared libraries (dask and distributed in particular) so as to avoid weird pickling and protocol issues.

**Comment by danielfrg** [comment]
I agree with everything. I have updated the Dockerfile to be based on python 3.6 and should be done once Docker hub builds the image.

The `environment.yml` is very easy to do, the only problem I have is that I am not sure what the best way to support this. Do you think it should support downloading the file: `wget ...` and then create the environment or just check if the file is somewhere and use it that file, in this second case the file would get shared as a volume. The second option sounds a little better to me in the case of the helm chart since people could just use a config-map. I guess it could support both.

To support this in the Jupyter notebook container we need to also provide an image that runs it, I am not sure if it should be based on the Jupyter ones (probably yes) or create a custom simple one.

**Comment by jakirkham** [comment]
Sounds like this is resolved, right? Is it ok to close?

**Comment by ogrisel** [comment]
LGTM, closing.
