### ISSUE TITLE
Update docker images to dask 2.6

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-docker#62]
We should probably update both dask, and also numpy=1.17.2 and pandas=0.25.1 . 

I tried doing this locally but ended up running into some jupyterlab conflicts, so I thought I'd raise an issue.

@jacobtomlinson any interest in handling this?  Also, any interest in automating this process?

**Comment by ryanrussell** [comment]
Just a comment on this.

The current Dockerfile fails with a fresh pull and 'docker-compose up' as current constructed(Pinned to 2.3.0)

See this thread: https://github.com/dask/dask/issues/5465

I was able to manually build just fine pinning to 2.5.2 instead of 2.3.0, but not sure about breaking changes and the reasons dask and pandas are pinned the way they currently are.
